### PR TITLE
If can return a type

### PR DESCRIPTION
**Pull request by basile-henry**
Implements https://github.com/dhall-lang/dhall-lang/pull/1090

And I believe this is all we need to be compliant with the upcoming standard v20.0.0: https://github.com/dhall-lang/dhall-lang/pull/1116 :smile:

### CODE REVIEW

**Comment by Nadrieril** [comment]
Did you get annoyed at direnv telling you to allow it in this folder? ^^ Looks good, and that means v20 won't need to be a breaking change :)

**Comment by basile-henry** [comment]
Well, I started using `direnv` (I would manually open a `nix-shell` before). And I don't want to accidentally commit it's state directory.

Admittedly it probably wasn't the right PR to do this in 😅

**Comment by Nadrieril** [comment]
Oh, I thought you gitignored `.envrc` sorry. I don't have a `.direnv` state directory, I'm surprised you do

**Comment by basile-henry** [comment]
Oh, I think it's because I use https://github.com/nix-community/nix-direnv
Since you also use nix, maybe you should check it out 😄

**Comment by Nadrieril** [comment]
I use lorri, which I prefer because it builds the environments in the background. Also you can apparently move the `.direnv` out of the project directory: https://github.com/nix-community/nix-direnv#storing-direnv-outside-the-project-directory

**Pull request merged**
