### PR TITLE
limit pest_consume to 1.0.4 since 1.0.5 is broken

### PR DESCRIPTION
**Pull request by Qeenon**

### CODE REVIEW

**Comment by Nadrieril** [comment]
1.0.5 is no more broken than 1.0.4 as far as I'm aware. Have you had any trouble building this from scratch? If there was, `crates.io` would not have allowed me to publish it

**Comment by Qeenon** [comment]
@Nadrieril I can't build my project which is depending on dhall because of error there https://github.com/Nadrieril/pest_consume/issues/7#issuecomment-718128823

**Comment by Nadrieril** [comment]
@Qeenon are you trying to build from source then? I believe the fix is to **not** run `cargo update` before building. If you have already done it, `git checkout Cargo.lock` should undo that

**Comment by Qeenon** [comment]
@Nadrieril I'm building my project, there is where I use dhall: https://github.com/Qeenon/Amadeus/blob/mawa/Cargo.toml#L29

and it fails to build pest_consume with that error

**Comment by Nadrieril** [comment]
pest_consume 1.0.6 fixes the issue. So I guess your code should build now? You may need to `cargo update`

**Pull request closed without merging**
