### PR TITLE
Fix reading file with a path relative to HOME

### LINKED ISSUE #223: home-anchored imports don't work
Forwarded from https://github.com/s-zeng/dhall-python/issues/41

According to the dhall documentation, the dhall language supports home-anchored imports as shown in the following example. dhall-rust however seems to support only the relative and absolute imports, but not the home-anchored import.

```
> dhall <<< '~/test.dhall'
"hello"

> cat src/main.rs
fn main() {
    let str_a = "./test.dhall";
    let str_b = "~/test.dhall";
    let local_test = serde_dhall::from_str(str_a).parse::<String>();
    let home_test = serde_dhall::from_str(str_b).parse::<String>();
    println!("Local import: {:?}", local_test);
    println!("Home import: {:?}", home_test);
}

> cargo run
Local import: Ok("hello")
Home import: Err(Error(Dhall(Error { kind: Typecheck(TypeError { message: Custom("error: error\n --> <current file>:1:1\n  |\n1 | ~/test.dhall\n  | ^^^^^^^^^^^^ No such file or directory (os error 2)\n  |") }) })))
```

Tested with serde_dhall 0.10

Thank you @padhla for reporting

### PR DESCRIPTION
**Pull request by basile-henry**
Fixes #223

We need to actually resolve the `~` in the path, this is not something supported by the `std::fs::File` API.

It looks like `dhall-haskell` does this as well:
https://github.com/dhall-lang/dhall-haskell/blob/14ae4296874fa9bdd4b585f0ef82d43cff36b091/dhall/src/Dhall/Import.hs#L475-L477

Maybe we should add some tests to cover this?
At the moment all import tests are relative, doing otherwise in the `dhall-lang` repo would be tricky as it would rely on knowing where the file are located.
But we should be able to do the following in this test suite: for all import tests, parse and convert imports to absolute imports and to relative to home imports, serialize and then test that.

### CODE REVIEW

**Comment by Nadrieril** [comment]
Looks good, but you're right we need tests. We should set "$HOME" to point to `dhall/tests` in the test harness and then try to import things.

**Comment by Nadrieril** [comment]
Looks perfect!

**Comment by padhia** [comment]
Sorry if I am being too impatient, but are you able to share an approximate timeline of the next release that includes this fix? 

PS: my interest in having this fix rolled out is due to s-zeng/dhall-python#41

**Comment by Nadrieril** [comment]
@padhia oh yeah don't hesistate to ask!
Here you go, v0.11.0 is out

**Comment by padhia** [comment]
Thank you!

**Pull request merged**
