### PR TITLE
Propagate reqwest feature to serde_dhall

### PR DESCRIPTION
**Pull request by basile-henry**

### CODE REVIEW

**Comment by rushsteve1** [comment]
From my testing this doesn't appear to have worked. Changing the dependency to...
```toml
serde_dhall = {
            git = "https://github.com/basile-henry/dhall-rust/",
            branch = "optional-reqwest",
            default-features = false
            }
```
Doesn't change the number of built dependencies, the size of the release binary, or the output of `cargo tree`.

**Comment by basile-henry** [comment]
Thanks for testing! I was building it from within `serde_dhall` directory and I couldn't see reqwest in the dependencies. I don't know if `default-features` works when building from the root of the project. At least cargo CLI doesn't allow the use of `--no-default-features` from there.

**Review by Nadrieril — APPROVED** [review]

**Comment by Nadrieril** [comment]
Oh I thought this would work :( My reading of the cargo docs says it should.
@rushsteve1 do you by any chance have another dependency that would depend on dhall?

**Comment by basile-henry** [comment]
I replicated your way of getting `serde_dhall` @rushsteve1 and I believe it works:

```bash
test-bin via 🦀 v1.43.1
➜ cargo tree | grep reqwest
└── serde_dhall v0.7.1 (git+https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa03beb5dc7048fe8db7be258f9b4a24d8)
    ├── dhall v0.7.0 (git+https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa03beb5dc7048fe8db7be258f9b4a24d8)
    │   ├── abnf_to_pest v0.5.0 (git+https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa03beb5dc7048fe8db7be258f9b4a24d8)
    ├── dhall_proc_macros v0.5.0 (git+https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa03beb5dc7048fe8db7be258f9b4a24d8)
```

No mentions of the reqwest package in the `cargo-tree` output. And I have check it is there when using the default features  😄

**Comment by rushsteve1** [comment]
Here are my files and outputs 

`Cargo.toml`
```
[dependencies]
serde = { version = "^1.0", features = ["derive"] }
rust-crypto = "^0.2"
# serde_dhall = "^0.7"
serde_dhall = {
            git = "https://github.com/basile-henry/dhall-rust/",
            branch = "optional-reqwest",
            default-features = false
            }
serde_json = "^1.0"
structopt = "^0.3"
dirs = "^3.0"
```

`cargo tree | grep reqwest`
```
├── serde_dhall v0.7.1 (https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa)
│   ├── dhall v0.7.0 (https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa)
│   │   ├── reqwest v0.10.8
│   │   ├── abnf_to_pest v0.5.0 (https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa)
│   ├── dhall_proc_macros v0.5.0 (https://github.com/basile-henry/dhall-rust/?branch=optional-reqwest#b1f0ccaa)
```

**Comment by rushsteve1** [comment]
I figured it out, I had a mistake in my `Cargo.toml`. The current version by @basile-henry does work!

**Comment by Nadrieril** [comment]
Oh wait, I know why it failed in the first place: I had not released a version of `dhall` since @basile-henry's PR making the feature work, I had only released a version of `serde_dhall` ><

**Comment by Nadrieril** [comment]
I just released `0.7.2`, properly this time. Should be fixed

**Pull request merged**
